### ISSUE TITLE
Feature Request: 2 Layers of Direrctories

### ISSUE THREAD

**Issue by jcavejr** [pimterry/notes#1]
I haven't actually used this yet as I just saw the reddit post, so forgive me if this feature already exists!

I'd like to see if it's possible to add 2 layers of directories, such as a layer of notebooks and inside each notebook have a layer of sections. This would make it easier to use for taking notes in University, I'd have a notebook for each class, a section for each chapter, and each individual file would be like a page. (Microsoft OneNote already has this, and it's the only feature holding me back from using this program over OneNote).

Thanks for reading and I hope you like the idea!

**Comment by pimterry** [comment]
You can already manage nested directories of notes with this. There's no special support for it built in (I'd like to add a nice tree view, and an easy way to explore that tree, etc), but the basics should just work as you'd expect.

For example:

```bash
# Open a new note in two folders down, creating folders if required:
notes new class1/chapter3/my-new-notes

# Find all notes from chapter 3:
notes find class1/chapter3

# Open a specific note:
notes open class1/chapter3/yesterdays-note
```

Is that what you're looking for?

**Comment by jcavejr** [comment]
Ohh gotcha, yes that's exactly what I was looking for. I'll probably start using this daily next semester :)

**Comment by pimterry** [comment]
Awesome! Let me know how it goes :+1:
