### ISSUE TITLE
Option to just print the note and exit, like cat command

### ISSUE THREAD

**Issue by nndurj** [pimterry/notes#37]
Hi, I added option **cat** to just print the note and exit. using https://github.com/axiros/terminal_markdown_viewer to prettify. Personally I find it useful. Do you think others might like it?

**Comment by pimterry** [comment]
This has come up before, see https://github.com/pimterry/notes/issues/9.

To summarize: you can nearly do this already with just existing tools, and once #23 is sorted you'll will be able to do things like `notes find <pattern> | xargs cat` to find and print notes already.

I'm trying to avoid baking things into `notes` that could be done by composing tools outside, to let the use cases evolve, and then slowly merge in the cases where there's clear substantial value.

That doesn't cover the prettification part, but you should be able to replace `xargs cat` with `xargs <my-content-viewer>` fairly easily to do what you're looking for. Would that solve your problem?

**Comment by nndurj** [comment]
I already added a command `notes cat <notesName>` for myself. Also wrote a simple prettify app in go https://github.com/nnvn/mdcat/ . Was wondering if others would like it. But, as you said, if full path is given during pipe, separate option won't be needed.
