### ISSUE TITLE
ZSH autocompletion URL is a 404

### ISSUE THREAD

**Issue by primis** [pimterry/notes#40]
https://cdn.rawgit.com/pimterry/notes/v0.2.0/notes._notes spits out a 404. This breaks the line
`curl https://cdn.rawgit.com/pimterry/notes/v0.2.0/notes._notes > /usr/share/zsh/site-functions/_notes`

**Comment by pimterry** [comment]
Good catch, thanks, now fixed: https://github.com/pimterry/notes/commit/8ebe0aefdfdfc6057b7c16a7a871ab8d9dbd85ca
