### ISSUE TITLE
exits successfully($? is 0) when it fails to create notes

### ISSUE THREAD

**Issue by rmNULL** [pimterry/notes#55]
#### Issue Summary
When `$NOTES_DIRECTORY` is set to a *filename*, that already exists in the directory.
It opens a new note but fails to save it, and exits 0
(as the exit status depends on the editor)

#### Steps to Reproduce

1. touch /tmp/secret
2. env NOTES_DIRECTORY=/tmp/secret notes n leaks
3. edit and save(fails to save), quit forcefully.
4.  Once you are back at shell, `echo $?`

#### Expected Behavior
exit before opening the editor and ask user to set `NOTES_DIRECTORY` to a safe location.
ofc, exit with non-zero status

**Comment by pimterry** [comment]
So to be clear, you'd like `new` & `open` to check in advance whether NOTES_DIRECTORY is actually a directory, right? Sounds sensible to me if so, I'd accept a PR.

**Comment by rmNULL** [comment]
I feel it would be better if we check after reading the configuration file.
