### ISSUE TITLE
settting $NOTES_DIRECTORY does not affect program

### ISSUE THREAD

**Issue by epogrebnyak** [pimterry/notes#64]
#### Issue Summary

$NOTES_DIRECTORY does not affect program

#### Steps to Reproduce

- Ubuntu WSL, installing notes via curl
- > NOTES_DIRECTORY=some/directory
- > $NOTES_DIRECTORY shows

-bash: some/directory: Is a directory

- notes --help 

Your notes directory is /home/epo/notes. You can
override this by setting $NOTES_DIRECTORY to your preferred path.

**Comment by pimterry** [comment]
If you try `export NOTES_DIRECTORY=some/directory` instead, does it work? Export is required to set variables in bash that can be seen by child processes: https://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export

I think you'll also want to use an absolute path. If you use a relative path (like some/directory), then your note storage will depend on your current working directory.

**Comment by epogrebnyak** [comment]
Many thanks for the explanation - `export NOTES_DIRECTORY=/abspath/some/directory` works just fine! Perhaps I can do a PR to update readme on this, to clarify the setting for users like myself?
