### ISSUE TITLE
Feature Request: Add to AUR

### ISSUE THREAD

**Issue by hackervera** [pimterry/notes#7]

**Comment by pimterry** [comment]
I assume you mean the [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository)? I'm not an arch user myself, so I don't know how to do that, and I wouldn't easily be able to test it. It sounds like a good idea though, and I'm very open to you (or anybody else) who does want to have a go at doing that.

**Comment by jacobmischka** [comment]
I will probably do it tonight once I'm at my computer, unless someone else already has by then.

**Comment by jacobmischka** [comment]
Done https://aur.archlinux.org/packages/notes-git/

As the name suggests, this is a git package in that it clones from and installs directly from master.

If you do not want that we can always make another, but the name `notes` is already taken, so we'd have to think of some other name, and it would be a bit more work and updates would be less frequent.

**Comment by pimterry** [comment]
Great! I think that'll do nicely for the moment. I might think about more unique naming at some point and a better distribution approach (ideas welcome), but not right now. Thanks for this though.
