### ISSUE TITLE
Tag support for notes

### ISSUE THREAD

**Issue by bmorashad** [pimterry/notes#77]
### Feature Request
- Tag support for notes to find notes by tags

it would be really cool if we can add multiple tags to a note
This is already an awesome app tnx <3

**Comment by pimterry** [comment]
You could sort-of do this right now by just including `#mytag` at the end of your note, and searching with `notes grep '#mytag'`.

Is there a specific case where built-in support would work better?

If so, can you give me an example of the UX you'd like for that? Do you want something you can write inline in the note, or a `notes tag <notename> <tag>` command, or something else?

**Comment by bmorashad** [comment]
Ahaaa yes! I can use that actually. I think that's enough for my use-case...Cool!
`notes tag <notename> <tag>` might be convenient to add tags, but not necessary for my use case. Actually I could make an _alias_ to do that ;)

**Comment by drewdaemon** [comment]
My 2 🪙: it would be nice to have `notes` support tags officially.

Tags could be added to the body of a note via a pattern similar to Jekyll's [front matter](https://jekyllrb.com/docs/front-matter/) or as described above, via a hashtag.

Then, an option could be added to `find`

```zsh
notes find --tag="recipes"
```

The ability to add tags via the command line as discussed above could be a nice bonus.

```
notes tag <notename> <tag>
```
